### ISSUE TITLE
Pass in the platform name to the command as the first argument. That should always be the first argument

### ISSUE THREAD

**Issue by Skarlso** [krok-o/krok#109]
To make it easier to detect what platform the event occurred on in the command, pass in the name of the platform, or the ID of the platform to the command.

If ID, then the command can import Krok and find out which platform that is so it's the same for every command.

**Comment by speza** [comment]
As discussed - it might also be worth looking into if we can provide a common model for the platforms. E.g. username, repo, etc.

**Comment by Skarlso** [comment]
@speza this is now done, right?

**Comment by Skarlso** [comment]
Positional arguments have been abandoned, we are passing them in correctly with `--platform` and the likes.
